name: gofetch-linter

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Running linter on ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0
    


